/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package program.phantomthiefjade;

import java.io.File;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.swing.ImageIcon;

/**
 *
 * @author barba
 */
public class YouHeartWillBeStolenAt24thHourTitleScreen extends javax.swing.JFrame {

    /**
     * Creates new form YouHeartWillBeStolenAt24thHourTitleScreen
     */
    public YouHeartWillBeStolenAt24thHourTitleScreen() {
        initComponents();
        setLocationRelativeTo(null);
         String startSound = "Start.wav";
         PlaySounEffect(startSound);
         String backgroundMusic = "Background.wav";
            try {
            Thread.sleep(500);
        } catch (InterruptedException ex) {
            Logger.getLogger(YouHeartWillBeStolenAt24thHourTitleScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
         PlayMusic(backgroundMusic);
    }
     public void icone (){
     ImageIcon icone = new ImageIcon ("icone.png");
     
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        PainelDeCima = new javax.swing.JPanel();
        PainelDeBaixo = new javax.swing.JPanel();
        BotaoComeca = new javax.swing.JLabel();
        BotaoCarrega = new javax.swing.JLabel();
        BotaoOpcao = new javax.swing.JLabel();
        BotaoExtra = new javax.swing.JLabel();
        BotaoSair = new javax.swing.JLabel();
        PinkClover = new javax.swing.JLabel();
        DisplayImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Your Heart Will be Stolen at 24th Hour");
        setResizable(false);

        jLayeredPane1.setBackground(new java.awt.Color(0, 0, 0));

        PainelDeCima.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout PainelDeCimaLayout = new javax.swing.GroupLayout(PainelDeCima);
        PainelDeCima.setLayout(PainelDeCimaLayout);
        PainelDeCimaLayout.setHorizontalGroup(
            PainelDeCimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        PainelDeCimaLayout.setVerticalGroup(
            PainelDeCimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 94, Short.MAX_VALUE)
        );

        PainelDeBaixo.setBackground(new java.awt.Color(0, 0, 0));

        BotaoComeca.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 18)); // NOI18N
        BotaoComeca.setForeground(new java.awt.Color(255, 255, 255));
        BotaoComeca.setText("Começar");
        BotaoComeca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotaoComecaMouseClicked(evt);
            }
        });

        BotaoCarrega.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 18)); // NOI18N
        BotaoCarrega.setForeground(new java.awt.Color(255, 255, 255));
        BotaoCarrega.setText("Carregar");
        BotaoCarrega.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotaoCarregaMouseClicked(evt);
            }
        });

        BotaoOpcao.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 18)); // NOI18N
        BotaoOpcao.setForeground(new java.awt.Color(255, 255, 255));
        BotaoOpcao.setText("Opções");
        BotaoOpcao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotaoOpcaoMouseClicked(evt);
            }
        });
        BotaoOpcao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BotaoOpcaoKeyPressed(evt);
            }
        });

        BotaoExtra.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 18)); // NOI18N
        BotaoExtra.setForeground(new java.awt.Color(255, 255, 255));
        BotaoExtra.setText("Extras");
        BotaoExtra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotaoExtraMouseClicked(evt);
            }
        });

        BotaoSair.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 18)); // NOI18N
        BotaoSair.setForeground(new java.awt.Color(255, 255, 255));
        BotaoSair.setText("Sair");
        BotaoSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotaoSairMouseClicked(evt);
            }
        });

        PinkClover.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        PinkClover.setForeground(new java.awt.Color(255, 255, 255));
        PinkClover.setText("Copyright @ PinkClover 2004 All Rights Reserved");

        javax.swing.GroupLayout PainelDeBaixoLayout = new javax.swing.GroupLayout(PainelDeBaixo);
        PainelDeBaixo.setLayout(PainelDeBaixoLayout);
        PainelDeBaixoLayout.setHorizontalGroup(
            PainelDeBaixoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelDeBaixoLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(BotaoComeca)
                .addGap(49, 49, 49)
                .addComponent(BotaoCarrega)
                .addGap(49, 49, 49)
                .addComponent(BotaoOpcao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BotaoExtra)
                .addGap(54, 54, 54)
                .addComponent(BotaoSair)
                .addGap(80, 80, 80))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelDeBaixoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PinkClover)
                .addContainerGap())
        );
        PainelDeBaixoLayout.setVerticalGroup(
            PainelDeBaixoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelDeBaixoLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(PainelDeBaixoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotaoComeca)
                    .addComponent(BotaoCarrega)
                    .addComponent(BotaoOpcao)
                    .addComponent(BotaoExtra)
                    .addComponent(BotaoSair))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(PinkClover)
                .addContainerGap())
        );

        DisplayImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ptj1.png"))); // NOI18N
        DisplayImage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLayeredPane1.setLayer(PainelDeCima, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(PainelDeBaixo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(DisplayImage, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelDeCima, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(PainelDeBaixo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(DisplayImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addComponent(PainelDeCima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(DisplayImage, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(PainelDeBaixo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );

        getAccessibleContext().setAccessibleDescription("Title Screen");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotaoComecaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoComecaMouseClicked
         String clickedeffect = "ButtonEffect.wav";
         PlaySounEffect(clickedeffect);      
    }//GEN-LAST:event_BotaoComecaMouseClicked

    private void BotaoCarregaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoCarregaMouseClicked
       String clickedeffect = "ButtonEffect.wav";
         PlaySounEffect(clickedeffect);   
    }//GEN-LAST:event_BotaoCarregaMouseClicked

    private void BotaoOpcaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BotaoOpcaoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotaoOpcaoKeyPressed

    private void BotaoOpcaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoOpcaoMouseClicked
     String clickedeffect = "ButtonEffect.wav";
         PlaySounEffect(clickedeffect);   
    }//GEN-LAST:event_BotaoOpcaoMouseClicked

    private void BotaoExtraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoExtraMouseClicked
      String clickedeffect = "ButtonEffect.wav";
         PlaySounEffect(clickedeffect);   
    }//GEN-LAST:event_BotaoExtraMouseClicked

    private void BotaoSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoSairMouseClicked
        String clickedeffect = "ButtonEffect.wav";
         PlaySounEffect(clickedeffect);   
         System.exit(WIDTH);
    }//GEN-LAST:event_BotaoSairMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(YouHeartWillBeStolenAt24thHourTitleScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(YouHeartWillBeStolenAt24thHourTitleScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(YouHeartWillBeStolenAt24thHourTitleScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(YouHeartWillBeStolenAt24thHourTitleScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new YouHeartWillBeStolenAt24thHourTitleScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BotaoCarrega;
    private javax.swing.JLabel BotaoComeca;
    private javax.swing.JLabel BotaoExtra;
    private javax.swing.JLabel BotaoOpcao;
    private javax.swing.JLabel BotaoSair;
    private javax.swing.JLabel DisplayImage;
    private javax.swing.JPanel PainelDeBaixo;
    private javax.swing.JPanel PainelDeCima;
    private javax.swing.JLabel PinkClover;
    private javax.swing.JLayeredPane jLayeredPane1;
    // End of variables declaration//GEN-END:variables

    
    public static void PlaySounEffect (String local){
        try {
            File musicPath = new File (local);
            if (musicPath.exists()){
                AudioInputStream audioInput = AudioSystem.getAudioInputStream(musicPath);
                Clip clip = AudioSystem.getClip();
                clip.open(audioInput);
                clip.start();
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }
    
       public static void PlayMusic (String local){
        try {
            File musicPath = new File (local);
            if (musicPath.exists()){
                AudioInputStream audioInput = AudioSystem.getAudioInputStream(musicPath);
                Clip clip = AudioSystem.getClip();
                clip.open(audioInput);
                clip.start();
                clip.loop(Clip.LOOP_CONTINUOUSLY);
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }
}
